# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-01-05T06:07:41+00:00

from __future__ import annotations

import contextvars
import logging
from abc import ABC, abstractmethod
from datetime import date
from typing import Any, Optional, Union

from fastapi import APIRouter, FastAPI, Path
from pydantic import conint
from reggie_core import logs

from .models import (
    AiChatPostRequest,
    AiChatPostResponse,
    AlertsGetResponse,
    AlertsStatsGetResponse,
    ApiSearchGetResponse,
    DevicesDeviceIdGetResponse,
    DevicesDeviceIdHistoryGetResponse,
    DevicesGetResponse,
    DevicesStatsGetResponse,
    Error,
    Interval,
    LicensePlatesDistributionGetResponse,
    LicensePlatesRecentGetResponse,
    LicensePlatesStatsGetResponse,
    ObjectDetectionHourlyGetResponse,
    ObjectDetectionRecentGetResponse,
    ObjectDetectionSummaryGetResponse,
    Period,
    SortDirection,
    Type,
)

LOG = logs.logger(__file__)


class APIContract(ABC):
    """Abstract base class defining the API contract."""

    @abstractmethod
    def send_chat_message(
        self, body: AiChatPostRequest
    ) -> Union[AiChatPostResponse, Error]:
        """Send chat message to AI assistant"""
        ...

    @abstractmethod
    def get_alerts(
        self, type: Optional[Type] = None, limit: Optional[conint(ge=1, le=100)] = 50
    ) -> Union[AlertsGetResponse, Error]:
        """Get all alerts"""
        ...

    @abstractmethod
    def get_alert_stats(
        self,
    ) -> Union[AlertsStatsGetResponse, Error]:
        """Get alert statistics"""
        ...

    @abstractmethod
    def search_data(
        self,
        q: str,
        limit: Optional[conint(ge=1, le=1000)] = 50,
        offset: Optional[conint(ge=0)] = 0,
        sort_column: Optional[str] = None,
        sort_direction: Optional[SortDirection] = 'asc',
    ) -> Union[ApiSearchGetResponse, Error]:
        """Search data with natural language"""
        ...

    @abstractmethod
    def get_devices(
        self,
    ) -> Union[DevicesGetResponse, Error]:
        """Get all devices"""
        ...

    @abstractmethod
    def get_device_stats(
        self,
    ) -> Union[DevicesStatsGetResponse, Error]:
        """Get device statistics"""
        ...

    @abstractmethod
    def get_device_by_id(
        self, device_id: str = Path(..., alias='deviceId')
    ) -> Union[DevicesDeviceIdGetResponse, Error]:
        """Get device by ID"""
        ...

    @abstractmethod
    def get_device_history(
        self,
        device_id: str = Path(..., alias='deviceId'),
        hours: Optional[conint(ge=1, le=168)] = 24,
        interval: Optional[Interval] = 60,
    ) -> Union[DevicesDeviceIdHistoryGetResponse, Error]:
        """Get device historical data"""
        ...

    @abstractmethod
    def get_license_plate_distribution(
        self, period: Optional[Period] = 'today'
    ) -> Union[LicensePlatesDistributionGetResponse, Error]:
        """Get license plate state distribution"""
        ...

    @abstractmethod
    def get_recent_plates(
        self, limit: Optional[conint(ge=1, le=100)] = 20
    ) -> Union[LicensePlatesRecentGetResponse, Error]:
        """Get recent license plate detections"""
        ...

    @abstractmethod
    def get_license_plate_stats(
        self,
    ) -> Union[LicensePlatesStatsGetResponse, Error]:
        """Get license plate statistics"""
        ...

    @abstractmethod
    def get_hourly_detections(
        self, date: Optional[date] = None
    ) -> Union[ObjectDetectionHourlyGetResponse, Error]:
        """Get hourly detection activity"""
        ...

    @abstractmethod
    def get_recent_detections(
        self, limit: Optional[conint(ge=1, le=100)] = 20
    ) -> Union[ObjectDetectionRecentGetResponse, Error]:
        """Get recent object detections"""
        ...

    @abstractmethod
    def get_object_detection_summary(
        self, period: Optional[Period] = 'today'
    ) -> Union[ObjectDetectionSummaryGetResponse, Error]:
        """Get object detection summary"""
        ...


class GeneratedRouter:
    """Router generator that binds API routes to a given contract implementation."""

    def __init__(self, contract: APIContract, log_level=None):
        self.contract = contract
        self.log_level = logs.get_level(log_level, logging.DEBUG)[0]
        self.router = APIRouter()

        @self.router.post(
            "/ai/chat",
            response_model=AiChatPostResponse,
            responses={"400": {"model": Error}, "500": {"model": Error}},
            tags=['AI Chat'],
        )
        def _send_chat_message(body: AiChatPostRequest):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "send_chat_message",
                {"body": body},
            )
            return self.contract.send_chat_message(body)

        @self.router.get(
            "/alerts",
            response_model=AlertsGetResponse,
            responses={"500": {"model": Error}},
            tags=['Alerts'],
        )
        def _get_alerts(
            type: Optional[Type] = None, limit: Optional[conint(ge=1, le=100)] = 50
        ):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_alerts",
                {"type": type, "limit": limit},
            )
            return self.contract.get_alerts(type, limit)

        @self.router.get(
            "/alerts/stats",
            response_model=AlertsStatsGetResponse,
            responses={"500": {"model": Error}},
            tags=['Alerts'],
        )
        def _get_alert_stats():
            LOG.log(self.log_level, "api request:%s args=%s", "get_alert_stats", {})
            return self.contract.get_alert_stats()

        @self.router.get(
            "/api/search",
            response_model=ApiSearchGetResponse,
            responses={"400": {"model": Error}, "500": {"model": Error}},
            tags=['Search'],
        )
        def _search_data(
            q: str,
            limit: Optional[conint(ge=1, le=1000)] = 50,
            offset: Optional[conint(ge=0)] = 0,
            sort_column: Optional[str] = None,
            sort_direction: Optional[SortDirection] = 'asc',
        ):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "search_data",
                {
                    "q": q,
                    "limit": limit,
                    "offset": offset,
                    "sort_column": sort_column,
                    "sort_direction": sort_direction,
                },
            )
            return self.contract.search_data(
                q, limit, offset, sort_column, sort_direction
            )

        @self.router.get(
            "/devices",
            response_model=DevicesGetResponse,
            responses={"500": {"model": Error}},
            tags=['Devices'],
        )
        def _get_devices():
            LOG.log(self.log_level, "api request:%s args=%s", "get_devices", {})
            return self.contract.get_devices()

        @self.router.get(
            "/devices/stats",
            response_model=DevicesStatsGetResponse,
            responses={"500": {"model": Error}},
            tags=['Devices'],
        )
        def _get_device_stats():
            LOG.log(self.log_level, "api request:%s args=%s", "get_device_stats", {})
            return self.contract.get_device_stats()

        @self.router.get(
            "/devices/{deviceId}",
            response_model=DevicesDeviceIdGetResponse,
            responses={"404": {"model": Error}, "500": {"model": Error}},
            tags=['Devices'],
        )
        def _get_device_by_id(device_id: str = Path(..., alias='deviceId')):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_device_by_id",
                {"device_id": device_id},
            )
            return self.contract.get_device_by_id(device_id)

        @self.router.get(
            "/devices/{deviceId}/history",
            response_model=DevicesDeviceIdHistoryGetResponse,
            responses={"404": {"model": Error}, "500": {"model": Error}},
            tags=['Devices'],
        )
        def _get_device_history(
            device_id: str = Path(..., alias='deviceId'),
            hours: Optional[conint(ge=1, le=168)] = 24,
            interval: Optional[Interval] = 60,
        ):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_device_history",
                {"device_id": device_id, "hours": hours, "interval": interval},
            )
            return self.contract.get_device_history(device_id, hours, interval)

        @self.router.get(
            "/license-plates/distribution",
            response_model=LicensePlatesDistributionGetResponse,
            responses={"500": {"model": Error}},
            tags=['License Plates'],
        )
        def _get_license_plate_distribution(period: Optional[Period] = 'today'):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_license_plate_distribution",
                {"period": period},
            )
            return self.contract.get_license_plate_distribution(period)

        @self.router.get(
            "/license-plates/recent",
            response_model=LicensePlatesRecentGetResponse,
            responses={"500": {"model": Error}},
            tags=['License Plates'],
        )
        def _get_recent_plates(limit: Optional[conint(ge=1, le=100)] = 20):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_recent_plates",
                {"limit": limit},
            )
            return self.contract.get_recent_plates(limit)

        @self.router.get(
            "/license-plates/stats",
            response_model=LicensePlatesStatsGetResponse,
            responses={"500": {"model": Error}},
            tags=['License Plates'],
        )
        def _get_license_plate_stats():
            LOG.log(
                self.log_level, "api request:%s args=%s", "get_license_plate_stats", {}
            )
            return self.contract.get_license_plate_stats()

        @self.router.get(
            "/object-detection/hourly",
            response_model=ObjectDetectionHourlyGetResponse,
            responses={"500": {"model": Error}},
            tags=['Object Detection'],
        )
        def _get_hourly_detections(date: Optional[date] = None):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_hourly_detections",
                {"date": date},
            )
            return self.contract.get_hourly_detections(date)

        @self.router.get(
            "/object-detection/recent",
            response_model=ObjectDetectionRecentGetResponse,
            responses={"500": {"model": Error}},
            tags=['Object Detection'],
        )
        def _get_recent_detections(limit: Optional[conint(ge=1, le=100)] = 20):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_recent_detections",
                {"limit": limit},
            )
            return self.contract.get_recent_detections(limit)

        @self.router.get(
            "/object-detection/summary",
            response_model=ObjectDetectionSummaryGetResponse,
            responses={"500": {"model": Error}},
            tags=['Object Detection'],
        )
        def _get_object_detection_summary(period: Optional[Period] = 'today'):
            LOG.log(
                self.log_level,
                "api request:%s args=%s",
                "get_object_detection_summary",
                {"period": period},
            )
            return self.contract.get_object_detection_summary(period)


def create_app(contract: APIContract, info: dict[str, Any] | None = None) -> FastAPI:
    """Creates a FastAPI app with router included."""
    app = FastAPI(**(info or {}))
    router = GeneratedRouter(contract)
    app.include_router(router.router)
    return app
